apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-guestbook:dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/robsonbezerraff/eks-workshop-template'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    namespace: guestbook-dev
    name: eks-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
